server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    fetch-registry: false #关闭eureka 立即注册 等启动完在注册
    register-with-eureka: false #让当前服务仅仅是祖册中心，不会注册
#这时这个SpringBoot服务的名字
spring:
  application:
    name: eurekaserver